version: 2
updates:
  - package-ecosystem: mix
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: mix
    open-pull-requests-limit: 0
    directory: "/demo"
    schedule:
      interval: weekly
      day: saturday
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: "/demo/assets"
    schedule:
      interval: weekly
      day: saturday
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: docker
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
